"""Variable file to hold global configuration details for web tests"""
OBJECT_SYNC_MIN_TIMEOUT = 15
OBJECT_SYNC_AVG_TIMEOUT = 20
OBJECT_SYNC_MAX_TIMEOUT = 25
PAGE_LOAD_MIN_TIMEOUT = 5
PAGE_LOAD_AVG_TIMEOUT = 10
PAGE_LOAD_MAX_TIMEOUT = 15
INVISIBILITY_MIN_TIMEOUT = 10
INVISIBILITY_AVG_TIMEOUT = 15
INVISIBILITY_MAX_TIMEOUT = 20
BROWSER = "chrome"
APP_URL = "http://the-internet.herokuapp.com/"
